# Generated by Django 4.2.16 on 2024-09-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP-адрес')),
                ('date', models.DateTimeField(verbose_name='дата из лога')),
                ('http_method', models.CharField(max_length=255, verbose_name='http метод')),
                ('uri_request', models.CharField(max_length=255, verbose_name='uri запроса')),
                ('code', models.IntegerField(verbose_name='код ответа')),
                ('size', models.IntegerField(verbose_name='размер ответа')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
