# Generated by Django 4.2.16 on 2024-09-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('pk',), 'verbose_name': 'лог', 'verbose_name_plural': 'логи'},
        ),
    ]
